create table if not exists consumer_user (
user_id int not null primary key auto_increment,
user_name varchar(100),
user_sex varchar(1),
user_age number(3) not null default 0,
user_id_no varchar(36),
user_phone_num varchar(24),
user_address varchar(128) not null default 'CHINA',
user_email varchar(64),
create_time date,
modify_time date,
user_active_state varchar(1) not null default 'Y');

DROP TABLE IF EXISTS mobile_food_facility_permit;
create table if not exists mobile_food_facility_permit (
  id int not null primary key auto_increment,
  locationid varchar(255),
  Applicant varchar(255),
  FacilityType varchar(255),
  cnn varchar(255),
  LocationDescription varchar(255),
  Address varchar(255),
  blocklot varchar(255),
  block varchar(255),
  lot varchar(255),
  permit varchar(255),
  Status varchar(255),
  FoodItems varchar(255),
  X varchar(255),
  Y varchar(255),
  Latitude varchar(255),
  Longitude varchar(255),
  Schedule varchar(255),
  dayshours varchar(255),
  NOISent varchar(255),
  Approved varchar(255),
  Received varchar(255),
  PriorPermit varchar(255),
  ExpirationDate varchar(255),
  Location varchar(255),
  FirePreventionDistricts varchar(255),
  PoliceDistricts varchar(255),
  SupervisorDistricts varchar(255),
  ZipCodes varchar(255),
  Neighborhoods varchar(255)
);